### ISSUE TITLE
Feedback on week 2 (not urgent)

### ISSUE THREAD

**Issue by mtdvlpr** [mtDvlpr/java-assignments#2]
I would like some feedback on my code. Specifically if anything can be written more efficiently, because I find my code a little complex and long at times. 
Also, is there a better way to deal with the possible exceptions (FileNotFoundException in DataInitializer & Main)? 
Now I just did what IntelliJ proposed.

**Comment by wimmelstein** [comment]
Hi Manoah,
There are many things you could do. One of the things you could you is create a class that stores the role. Once you're logged in it doesn't really matter who you are, but the role does. If you want some personalization, like saying "Welcome <insert name>, you could store the firstName, lastName and the role.
Then you could create something like a menu/menu-item class with what role can access which menu and menu-item. You can pass these, along with the scanner instance, to a console-view class, which can display the menu, based on the role.
Why don't you look at something like that?

**Comment by mtdvlpr** [comment]
Yes, that's helpful, thank you!
