### ISSUE TITLE
Check for a winner in tic-tac-toe

### ISSUE THREAD

**Issue by mtdvlpr** [mtDvlpr/java-assignments#3]
https://github.com/mtDvlpr/java-assignments/blob/be391300c393abfe90b2b2f0ad6718c77b7ad689/Week4/src/nl/inholland/TicTacToe.java#L126-L156

I think the way I am going about this is all wrong. Could you maybe steer me in the right direction?

**Comment by wimmelstein** [comment]
Hi. You are not thinking object oriented. First of all, we I told you all buttons are instances of nodes. You could iterate over all the nodes, and assign an action in one go. Furthermore you should think of a row or a colunn and a diiagonal like an object in itself. That would make 8 objects (three rows, three columns and two diagonals). Then you could check for a pattern. You could even dispense with the two dimensional arrays if you want, and look at it as one array of 9. [1][2][3] is row 1. [1][5][9] is diagonal one. That makes for easier checking. Also you could check for binding properties. If a button click changes the array value, that value can trigger a change of text on the button. Don't check the value of the button. Check the underlying array.
I hope this rambling made sense ...

**Comment by mtdvlpr** [comment]
Thanks for your reply! I will try and see if I can figure it out now. If and when I do, I will close the issue.

**Comment by mtdvlpr** [comment]
I got it working🥳! Not sure if I used the exact way you described, but thank you for your assistance! My working code:

    private boolean checkForWinner(Button[][] buttons, String player) {
        return checkRowColWin(buttons, player, true) || checkRowColWin(buttons, player, false) || checkDiagonalWin(buttons, player);
    }

    private boolean checkRowColWin(Button[][] buttons, String player, boolean checkRow) {
        for (int row = 0; row < buttons.length; row++) {
            int inARow = 0;
            for (int col = 0; col < buttons[0].length; col++) {
                if (checkRow) {
                    if (buttons[row][col].textProperty().getValue().equals(player)) {
                        inARow++;
                    }
                } else {
                    if (buttons[col][row].textProperty().getValue().equals(player)) {
                        inARow++;
                    }
                }
            }
            if (inARow == 3) {
                return true;
            }
        }
        return false;
    }

    private boolean checkDiagonalWin(Button[][] buttons, String player) {
        return diagonalWin(player, buttons[0][0], buttons[1][1], buttons[2][2]) || diagonalWin(player, buttons[0][2], buttons[1][1], buttons[2][0]);
    }

    private boolean diagonalWin(String player, Button btn1, Button btn2, Button btn3) {
        return btn1.textProperty().getValue().equals(player) && btn2.textProperty().getValue().equals(player) && btn3.textProperty().getValue().equals(player);
    }

    private boolean checkForTie(Button[][] buttons) {
        for (Button[] button : buttons) {
            for (int col = 0; col < buttons[0].length; col++) {
                if (button[col].textProperty().getValue().equals("_")) {
                    return false;
                }
            }
        }
        return true;
    }
